# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: campeonato-database
    image: mysql
    
    restart: always

    environment:
      MYSQL_DATABASE: campeonato
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
      
    volumes:
      - ./mysql:/var/lib/mysql